nfl_team = [
    {"name": "Arizona Cardinals", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png", "link": "https://www.espn.com/nfl/team/_/name/ari/arizona-cardinals"},
    {"name": "Atlanta Falcons", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png", "link": "https://www.espn.com/nfl/team/_/name/atl/atlanta-falcons"},
    {"name": "Baltimore Ravens", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png", "link": "https://www.espn.com/nfl/team/_/name/bal/baltimore-ravens"},
    {"name": "Buffalo Bills", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png", "link": "https://www.espn.com/nfl/team/_/name/buf/buffalo-bills"},
    {"name": "Carolina Panthers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/car.png", "link": "https://www.espn.com/nfl/team/_/name/car/carolina-panthers"},
    {"name": "Chicago Bears", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png", "link": "https://www.espn.com/nfl/team/_/name/chi/chicago-bears"},
    {"name": "Cincinnati Bengals", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png", "link": "https://www.espn.com/nfl/team/_/name/cin/cincinnati-bengals"},
    {"name": "Cleveland Browns", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png", "link": "https://www.espn.com/nfl/team/_/name/cle/cleveland-browns"},
    {"name": "Dallas Cowboys", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png", "link": "https://www.espn.com/nfl/team/_/name/dal/dallas-cowboys"},
    {"name": "Denver Broncos", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/den.png", "link": "https://www.espn.com/nfl/team/_/name/den/denver-broncos"},
    {"name": "Detroit Lions", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/det.png", "link": "https://www.espn.com/nfl/team/_/name/det/detroit-lions"},
    {"name": "Green Bay Packers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png", "link": "https://www.espn.com/nfl/team/_/name/gb/green-bay-packers"},
    {"name": "Houston Texans", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png", "link": "https://www.espn.com/nfl/team/_/name/hou/houston-texans"},
    {"name": "Indianapolis Colts", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png", "link": "https://www.espn.com/nfl/team/_/name/ind/indianapolis-colts"},
    {"name": "Jacksonville Jaguars", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png", "link": "https://www.espn.com/nfl/team/_/name/jax/jacksonville-jaguars"},
    {"name": "Kansas City Chiefs", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png", "link": "https://www.espn.com/nfl/team/_/name/kc/kansas-city-chiefs"},
    {"name": "Las Vegas Raiders", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png", "link": "https://www.espn.com/nfl/team/_/name/lv/las-vegas-raiders"},
    {"name": "Los Angeles Chargers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png", "link": "https://www.espn.com/nfl/team/_/name/lac/los-angeles-chargers"},
    {"name": "Los Angeles Rams", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png", "link": "https://www.espn.com/nfl/team/_/name/lar/los-angeles-rams"},
    {"name": "Miami Dolphins", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png", "link": "https://www.espn.com/nfl/team/_/name/mia/miami-dolphins"},
    {"name": "Minnesota Vikings", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/min.png", "link": "https://www.espn.com/nfl/team/_/name/min/minnesota-vikings"},
    {"name": "New England Patriots", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png", "link": "https://www.espn.com/nfl/team/_/name/ne/new-england-patriots"},
    {"name": "New Orleans Saints", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/no.png", "link": "https://www.espn.com/nfl/team/_/name/no/new-orleans-saints"},
    {"name": "New York Giants", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png", "link": "https://www.espn.com/nfl/team/_/name/nyg/new-york-giants"},
    {"name": "New York Jets", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png", "link": "https://www.espn.com/nfl/team/_/name/nyj/new-york-jets"},
    {"name": "Philadelphia Eagles", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png", "link": "https://www.espn.com/nfl/team/_/name/phi/philadelphia-eagles"},
    {"name": "Pittsburgh Steelers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png", "link": "https://www.espn.com/nfl/team/_/name/pit/pittsburgh-steelers"},
    {"name": "San Francisco 49ers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png", "link": "https://www.espn.com/nfl/team/_/name/sf/san-francisco-49ers"},
    {"name": "Seattle Seahawks", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png", "link": "https://www.espn.com/nfl/team/_/name/sea/seattle-seahawks"},
    {"name": "Tampa Bay Buccaneers", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png", "link": "https://www.espn.com/nfl/team/_/name/tb/tampa-bay-buccaneers"},
    {"name": "Tennessee Titans", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png", "link": "https://www.espn.com/nfl/team/_/name/ten/tennessee-titans"},
    {"name": "Washington Commanders", "logo": "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png", "link": "https://www.espn.com/nfl/team/_/name/wsh/washington-commanders"}
]